# Generated by Django 6.0.5 on 2026-06-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Catergory',
            new_name='category',
        ),
    ]
